; deployprobe.g
; called to deploy a physical Z probe
;
; generated by RepRapFirmware Configuration Tool on Mon Sep 17 2018 19:31:26 GMT-0700 (Pacific Daylight Time)
M280 P3 S160 I1 ; clear errors first
M280 P3 S10 I1