; tpost0.g
; called after tool 0 has been selected
;
; generated by RepRapFirmware Configuration Tool on Mon Sep 17 2018 19:31:26 GMT-0700 (Pacific Daylight Time)
; Wait for set temperatures to be reached
M116 P0